### ISSUE TITLE
detect iPad in iOS 13

### ISSUE THREAD

**Issue by tavelli** [chrisdancee/react-ios-pwa-prompt#15]
navigator.platform for iPad in iOS13 reports as "MacIntel". This is one hack to detect it by checking for touch screen

`navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1`

**Comment by chrisdancee** [comment]
Hi @tavelli, thanks for raising the issue and for the suggested fix. Feel free to push a PR for this change, else I will get round to it over the next couple of days.
