### ISSUE TITLE
Add possibility to translate every prompt string

### ISSUE THREAD

**Issue by Raysharr** [chrisdancee/react-ios-pwa-prompt#16]
Currently, we can translate the title and body of the prompt, but texts used for steps description are not translatable. I am talking about these two:
`1) Press the 'Share' button`
`2) Press 'Add to Home Screen'`

It would be great to pass them to a component as props like title and body of the prompt and set defaults to what you guys have in the code already.

Thanks.

**Comment by chrisdancee** [comment]
Hi @Raysharr,

This issue has been resolved by the work @konradhalo has done in the following commit: 

https://github.com/chrisdancee/react-ios-pwa-prompt/commit/21cd156d0028e55d28d1b5b6e9b22af827b0686b

This will be released today :)

**Comment by Raysharr** [comment]
Great to hear that. Thanks for letting me know :)
