### ISSUE TITLE
All other click events in page stop working

### ISSUE THREAD

**Issue by escobar5** [chrisdancee/react-ios-pwa-prompt#21]
I'm testing it in iOS 13, and after the prompt is shown, the other click events in the page stop working, if the prompt is not shown, everything works ok.

**Comment by chrisdancee** [comment]
Hi @escobar5, thank you for reporting this issue.

I don't currently have access to an iPad running iOS13, however I think I have fixed the issue in the following PR:

https://github.com/chrisdancee/react-ios-pwa-prompt/pull/22

Please could you retest the issue with v1.4.2 and let me know is this worked?

**Comment by escobar5** [comment]
Yes, that fixed it. Thanks!
