### ISSUE TITLE
When using with Chakra-UI CSSReset, box appears with white border

### ISSUE THREAD

**Issue by TransmissionsDev** [chrisdancee/react-ios-pwa-prompt#36]
Hey Chris!

Just want to start of by saying that this project is amazing, and thank you for all your hard work!

When using the component with Chakra-UI's CSSReset component (https://chakra-ui.com/getting-started), a weird border appears around the body text, removing the cool "native" feel. 

Here's a pic: https://i.imgur.com/Q0x5qwY.png

Any ideas to get around this?

**Comment by TransmissionsDev** [comment]
Alright I think I figured out the solution. 

The classes "pwaPromptHeader" and the class "pwaPromptDescription" need these styles applied to them:

```css
 border-top: 0px;
 border-left: 0px;
 border-right: 0px;
```

I'll create a pull request. However, if you think that there is a better solution, let me know :D

**Comment by chrisdancee** [comment]
Hi @TransmissionsDev, the change looks good to me. I'll get this released today. Thanks a lot for taking the time to report the issue and find a fix :)

**Comment by chrisdancee** [comment]
This has been tested, merged and published in 1.5.1 
Thanks again for your contribution :)
