### ISSUE TITLE
Demo / example available?

### ISSUE THREAD

**Issue by tahv0** [chrisdancee/react-ios-pwa-prompt#41]
Hi. Is there any website where I can test this? Thanks.

**Comment by TransmissionsDev** [comment]
@tahv0 Hey! My website: spotbok3.now.sh uses react-ios-pwa-prompt. Feel free to take a look at it :D

**Comment by tahv0** [comment]
> @tahv0 Hey! My website: https://spotbok3.now.sh uses react-ios-pwa-prompt. Feel free to take a look at it :D

404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND

Thanks man. But is that site working? My iPhone doesn't do anything with Safari 13.

**Comment by TransmissionsDev** [comment]
> > @tahv0 Hey! My website: https://spotbok3.now.sh uses react-ios-pwa-prompt. Feel free to take a look at it :D
> 
> 404: NOT_FOUND
> Code: DEPLOYMENT_NOT_FOUND
> 
> Thanks man. But is that site working? My iPhone doesn't do anything with Safari 13.

Oops! I missed an O in the url. It should be https://spotbook3.now.sh . Try that out and tell me if it works.

**Comment by chrisdancee** [comment]
Hi @tahv0,

Will look into adding a demo page, thank you for the suggestion.
