### ISSUE TITLE
Why so complex classNames?

### ISSUE THREAD

**Issue by tahv0** [chrisdancee/react-ios-pwa-prompt#42]
There is no way to customizate it out of component. I'm building PWA App that is forced to landscape mode via styles.

Could extra styles be given via props?

**Comment by TransmissionsDev** [comment]
Forking it might be the best option to customize. The class names are long due to CSS Minifciation.

**Comment by chrisdancee** [comment]
Hi @tahv0, 

As @TransmissionsDev explained (much appreciated btw!), the component uses CSS modules and minifies the classnames.

In the linked PR however, I have added semantic classes that you can select more easily using CSS. This will (very soon) be available in the next minor version if you upgrade. Hope this helps your particular use case and may prove useful for others. Thank you for raising the issue.

https://github.com/chrisdancee/react-ios-pwa-prompt/pull/44
