### ISSUE TITLE
Suggestion: hint the user to "swipe up" before press "Add to home screen"

### ISSUE THREAD

**Issue by TiFerr** [chrisdancee/react-ios-pwa-prompt#45]
Of course we can overwrite it with:
copyAddHomeButtonLabel={"2) Swipe up and press 'Add to Home Screen'"}

By the way, Nice Job!

**Comment by chrisdancee** [comment]
No longer necessary, as locking the page body forces the bottom navigation bar to be displayed.
Closing for now.
