### ISSUE TITLE
Suggestion: detect service worker

### ISSUE THREAD

**Issue by TarikHuber** [chrisdancee/react-ios-pwa-prompt#50]
What do you think about checking if a service worker is registered and only if one is show the dialog?

**Comment by TransmissionsDev** [comment]
@TarikHuber What's the need to do this? The current system works great for me.

**Comment by TarikHuber** [comment]
If the sw registration fails it could causs problems for the pwa installation. But I'm not sure if it would make problems on iOS. On Windos and Android the installation prompt that can be deffered comes after the SW registration and all PWA requirements are set. In 99 % of cases the sw should be registered until the user reads the installation dialog. But that little possible situation could also be covered.

**Comment by chrisdancee** [comment]
@TarikHuber thanks for raising the issue 🙂

I think this could be a premature optimisation of an issue that doesn’t generally exist. 

We could potentially use https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/active to detect whether the SW has initially registered, but would need to add some sort of timing side effect to retry until the SW was registered.

Personally I think that that is out of scope for this project, but think that the issue has some merit. 

I think maybe changing the debug prop to a ‘persist’ prop would allow the developer to take control of exactly when the prompt should show. You could then choose to display the prompt after the SW Promise has resolved. 

I will consider this some more, but for now I’m going to close this issue. Please feel free to reopen if you have examples of this problem and we can look to resolve.

**Comment by TarikHuber** [comment]
Thx @chrisdancee 😄 

Yea it might be to much for this project to handle it. I also solved it by wrapping it in a prop that activates the dialog only if a SW is registered and active.
