### ISSUE TITLE
iOS 14 detection

### ISSUE THREAD

**Issue by kffl** [chrisdancee/react-ios-pwa-prompt#57]
Hello everyone! I have to say, this library has great look and feel with superb attention to detail.

I was giving it a try this week and realized that it doesn't detect iOS 14 properly. The prompt uses pre-13 icons and is not influenced by the os's theme, take a look:

![iOS14-prompt-ss_04](https://user-images.githubusercontent.com/34161459/98470244-ac2fb580-21e4-11eb-8797-5595685f0c23.jpg)

I've prepared a little demo to demonstrate this issue: https://react-ios-pwa-prompt-example.netlify.app ([source](https://github.com/kffl/react-ios-pwa-prompt-example))

**Comment by TransmissionsDev** [comment]
Have also noticed this, great that you created a PR
