### ISSUE TITLE
Component appears as Anonymous and does not work

### ISSUE THREAD

**Issue by phtmgt** [chrisdancee/react-ios-pwa-prompt#75]
Imported the component per the provided instructions, but it does not function at all.

On react components inspection I can see an 'Anonymous' component instead of PWAPrompt.

Does not fire on iOS (iPhone / iPad) or on a faked user agent.

**Comment by e0c615c8e4d846ef817cd5063a88716c** [comment]
I also have this issue. Did you find a resolution?

**Comment by damianobarbati** [comment]
same for me, @phtmgt did you manage to solve?

**Comment by phtmgt** [comment]
I probably did, but it was so long ago I don’t remember the solution (or the exact issue for that matter) any more. Sorry I couldn’t help.
